services:
  rest-server:
    container_name: rest-server
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    hostname: rest-server
    environment:
      DBUSER: ${DBUSER:-root}
      DBPASS: ${DBPASS:?password not set}
      DBNAME: ${DBNAME:-testdb}
      DBCOLL: ${DBCOLL:-testcoll}
    networks:
      - itemsnet
    ports:
      - 6000:8080
    deploy:
      restart_policy:
        condition: on-failure
  db:
    image: mongo
    container_name: db1
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DBUSER}
      MONGO_INITDB_ROOT_PASSWORD: ${DBPASS}
      MONGO_INITDB_DATABASE: ${DBNAME}
    ports:
      - 27017:27017
    volumes:
      - itemsdb:/data/db
    networks:
      - itemsnet

volumes:
  itemsdb:    
    
networks:
  itemsnet:
